[package]
authors = ['Doug Stephen <dljs.jr@dougstephenjr.com']
edition = '2021'
license = 'Apache-2.0'
name = 'undump-aya-common'
version = '0.1.0'

[dependencies.aya]
optional = true
version = '0.12'

[features]
default = []
user = ['aya']

[lib]
path = 'src/lib.rs'
